project:
  type: website
  output-dir: docs

brand: brand/_brand.yml

execute:
  python: .venv/Scripts/python.exe
  
website:
  title: "LUDataLiteracy"
  page-footer:
    left: 'Lund University'
    right: "Data Literacy with Python"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Practicals"
        menu:
          - 1_DataViz.qmd
          - 2_DataViz_wrangling.qmd
          - 3_Wrangling_GT.qmd
          - 4_Wrangling_joins.qmd
          - 5_Pivots_GT.qmd
          - 6_Quarto.qmd
      - text: "Solutions"
        menu:
          - 1_DataViz_sol.qmd
          - 2_DataViz_wrangling_sol.qmd
          - 3_Wrangling_GT_sol.qmd
      - text: "Data"
        menu:
          - Utrecht.qmd
          - KingsCounty.qmd
          - CIA.qmd
      - about.qmd

format:
  html:
    page-layout: full
    grid: 
      body-width: 1000px
    theme: [zephyr, brand]
    anchor-sections: true
    email-obfuscation: javascript
    toc: true
    link-external-icon: true
    link-external-newwindow: true

custom-callout:
  challenge:
    icon-symbol: "üõ†Ô∏è"
    color: "firebrick"
  question:
    icon-symbol: "üß†"
    color: "pink"
filters:
  - custom-callout



# format:
#   html:
#     theme:
#       - cosmo
#       - brand
#     css: styles.css
#     toc: true
# 
# editor: visual

